[features]
seeds = false
skip-lint = false
[programs.localnet]
stockpile = "STKYsPcbyMG1uHrMX56t1aDqSv4e5qGt9DMk693BCeZ"
[programs.devnet]
stockpile = "STKYsPcbyMG1uHrMX56t1aDqSv4e5qGt9DMk693BCeZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/target/deploy/stockpile-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
