[features]
seeds = false
skip-lint = false
[programs.localnet]
stockpile = "2V5SzQwXGMZCaK25kuv7xvbah4GVA7h7i15CEZpCPgKQ"
[programs.devnet]
stockpile = "2V5SzQwXGMZCaK25kuv7xvbah4GVA7h7i15CEZpCPgKQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/target/deploy/stockpile-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
