[features]
seeds = false
skip-lint = false
[programs.localnet]
stockpile = "STKqgkK72R1sJhV4BTipUcKkMFougtdTuDMr2RVubKr"
[programs.devnet]
stockpile = "STKqgkK72R1sJhV4BTipUcKkMFougtdTuDMr2RVubKr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
