[features]
seeds = false
skip-lint = false
[programs.localnet]
stockpile = "48SQXcY7zxJhKdSLNNfh5pou9zwmJLnViFmAmmEKxrtt"
[programs.devnet]
stockpile = "48SQXcY7zxJhKdSLNNfh5pou9zwmJLnViFmAmmEKxrtt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/target/deploy/stockpile-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
