[features]
seeds = false
skip-lint = false
[programs.localnet]
stockpile = "CVhwkyv1yyHVwTSdTmbHSZ7HG5zNjBwxYP6gaJiX4FpA"
[programs.devnet]
stockpile = "CVhwkyv1yyHVwTSdTmbHSZ7HG5zNjBwxYP6gaJiX4FpA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/target/deploy/stockpile-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
